### PR TITLE
Revert "DankMemes"

### PR DESCRIPTION
**Pull request by binn**
im such a retard give me a moment.

### CODE REVIEW

**Comment by zaida04** [comment]
Please be patient i have _AUTiSm_

**Comment by zaida04** [comment]
but did i do good bin senpai

**Comment by binn** [comment]
no like basically i merged this PR and i fucked up so remake the PR and redo ur changed and ill merge it xd

**Comment by zaida04** [comment]
there

**Comment by zaida04** [comment]
did it work?

**Comment by binn** [comment]
yes it did now get back to work nico lol check it out http://otako.moe/404.html
inb4 blocked on school wifi

**Comment by binn** [comment]
Locking this conversation since the issue is fixed.

**Pull request merged**
