### PR TITLE
Updated Front-end to use Vuejs

### PR DESCRIPTION
**Pull request by prydt**
Using a UI library like Vue will make making the front-end much easier when implementing the interface for the app itself. I have made a new Vue app from the bottom up with just a few components, but plan to port the layout of the login screen to here. 

I was also wondering, what kind of color scheme would be nice for the UI of Okato? (Light or Dark are usually the two themes debated about)

### CODE REVIEW

**Comment by Greek** [comment]
i wanna see how this works but, idk. i can just run it on localhost, rite?

**Comment by binn** [comment]
Should we merge?

**Comment by Greek** [comment]
no
we need the client version of the app
with the toolbar.

**Comment by prydt** [comment]
selection_003
selection_004
selection_005

these are the previews

**Comment by binn** [comment]
I have never felt so gay. It's joke. 
(but honestly a login page doesn't need themeing)

**Comment by prydt** [comment]
the drop-down is for debugging m8

**Comment by Greek** [comment]
yey menubar.io

**Pull request merged**
